name: "espressif idf build"
description: "This action build your firmware directly in github using Espressif idf SDK."
branding:
  color: blue
  icon: check
inputs:
  path:
    description: 'Relative path under $GITHUB_WORKSPACE to place the repository'
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
    - ${{ inputs.action }}
